#4822507: Implement the vertical divider and make the dividers configurable
buildo/bento-design-system pull request #153
Opened 2022-04-20 08:48 UTC by veej

Closes [#4822507](https://buildo.kaiten.io/4822507)

## Test Plan

### tests performed

> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.

### tests not performed (domain coverage)

> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

2022-04-20 08:53 UTC, veej commented on packages/bento-design-system/src/Divider/Divider.tsx
> +export function Divider({ orientation = "horizontal" }: Props) {
default is horizontal for retrocompatibility

2022-04-21 15:42 UTC, Phyele requested changes

2022-04-21 15:42 UTC, Phyele commented on packages/storybook/stories/index.tsx
> +    height: 3,
```suggestion
    height: 2,
```

2022-04-21 15:42 UTC, Phyele commented on packages/bento-design-system/src/util/defaultConfigs.tsx
> +  height: 1,
```suggestion
  height: 2,
```

2022-04-21 15:42 UTC, Phyele commented on packages/bento-design-system/src/util/defaultConfigs.tsx
> +  radius: 0,
```suggestion
  radius: "circledX",
```

2022-04-21 16:02 UTC, Phyele approved these changes

2022-04-21 16:08 UTC, gabro approved these changes

2022-04-21 16:08 UTC, merged