#472: Add support for units of measurement on BarChart component
buildo/bento-design-system pull request #476
Opened 2022-12-15 14:24 UTC by federico-ercoles

Closes #472

## Test Plan

### tests performed

> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.

### tests not performed (domain coverage)

> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

2022-12-16 10:40 UTC, gabro requested changes
See the inline comments.

Additionally, let's add it wherever makes sense (so also LineChart and DonutChart)

2022-12-16 10:40 UTC, gabro commented on packages/bento-design-system/src/Charts/BarChart/BarChart.tsx
> +  yAxisValueFormatter = defaultValueFormatter,
why do we need a `defaultValueFormatter`? Can't we just pass `undefined`?

2022-12-16 10:40 UTC, gabro commented on packages/bento-design-system/src/Charts/Tooltip/Tooltip.tsx
> +};
I think we can use the standard `formatter` value from `Tooltip`. If we do that we can avoid this intermediate `TooltipComponent` wrapping and keep using `tooltipComponent` as before, and passing `yAxisValueFormatter` to `Tooltip` directly.

I have a working prototype (based on this branch) here: https://github.com/buildo/bento-design-system/compare/472-add_support_for_units-2?expand=1

Let me know what you think

2022-12-20 13:20 UTC, veej approved these changes

2022-12-20 16:09 UTC, gabro approved these changes

2022-12-20 16:09 UTC, merged