Use Vite builder in Storybook
buildo/bento-design-system pull request #749
Opened 2023-08-29 12:48 UTC by veej

2023-08-29 13:01 UTC, gabro approved these changes

2023-08-29 13:22 UTC, gabro requested changes
The Storybook build is failing due to a missing woff loader

2023-08-30 13:41 UTC, veej commented
@gabro moving the import of fonts in the `preview.ts` seems to fix the issue with the build

2023-08-30 14:10 UTC, gabro approved these changes

2023-08-30 14:10 UTC, merged